### ISSUE TITLE
import kaldi_asr_client failed!

### ISSUE THREAD

**Issue by qichilu** [antematter/kaldi-asr-client#1]
>>> import kaldi_asr_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data_hdd/share/clu/venv/triton/lib/python3.8/site-packages/kaldi_asr_client/__init__.py", line 1, in <module>
    from .kaldi_asr_client import Client, restart_servers
  File "/data_hdd/share/clu/venv/triton/lib/python3.8/site-packages/kaldi_asr_client/kaldi_asr_client.py", line 41, in <module>
    class Client:
  File "/data_hdd/share/clu/venv/triton/lib/python3.8/site-packages/kaldi_asr_client/kaldi_asr_client.py", line 92, in Client
    def infer(self, wavs: list[bytes]):
TypeError: 'type' object is not subscriptable

**Comment by saad039** [comment]
@qichilu We're not actively maintaining the repository but are you still facing the issue?
